### ISSUE TITLE
Why do we only look at pull requests, not all issues?

### ISSUE THREAD

**Issue by alexmuller** [alphagov/fourth-wall#1]
As a ______________, I want to know when somebody opens an issue on one of my projects so that I can respond in a timely manner and look super awesome.

I think pull requests are a subset of issues on GitHub?

**Comment by issyl0** [comment]
Thanks for the feature request. We're not planning on working on this app in the near future, but we'd happily review a PR if you wanted to have a go at implementing this yourself. 👍
