### ISSUE TITLE
A screenshot in the README would be really helpful

### ISSUE THREAD

**Issue by mattbostock** [alphagov/fourth-wall#13]
A screenshot in the README would be really helpful to visualise what this project does.

**Comment by issyl0** [comment]
Will this do, taken today? 
![screen shot 2015-02-16 at 11 45 01](https://cloud.githubusercontent.com/assets/355033/6211416/6341db4e-b5d1-11e4-99d2-57b80a400a41.png)

**Comment by mattbostock** [comment]
Looks good to me! :+1:
