### ISSUE TITLE
Internet connectivity indicator

### ISSUE THREAD

**Issue by tlwr** [alphagov/fourth-wall#68]
When run on build monitors, if they connect to the internet there is no visual indicator that something is wrong.

I hope to add something simple like this: (cribbed from Concourse-ci)

![screen shot 2018-12-04 at 13 37 44](https://user-images.githubusercontent.com/1482692/49445481-eb1f8a00-f7c9-11e8-8830-7374a396728d.png)

**Comment by alexmuller** [comment]
This is a good idea 👍
