### ISSUE TITLE
Can't filter on bot users

### ISSUE THREAD

**Issue by dwaynebailey** [alphagov/fourth-wall#87]
We're using dependabot but with the number of repos and open PRs these crowd out human contribution.  I tried making a dashboard just for dependenbot but you can't filter on the bot user at all.  Needs to ability to filter new style bots.

**Comment by issyl0** [comment]
Thanks for the feature request. We're not planning on working on this app in the near future, but we'd happily review a PR if you wanted to have a go at implementing this yourself. 👍
